version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.local
    container_name: studere-api
    volumes:
      - .:/home/fastapi/studere
      
  db:
    image: postgres:12-alpine
    container_name: studere-db
    tty: true
    environment:
      - POSTGRES_DB=studere
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432

volumes:
  postgres:
